grails-app/domain/encuestador/ListaControlada.groovy
package encuestador

class ListaControlada {

    String codigo

    String nombre

    static hasMany = [ valores: ValorListaControlada ]

    static constraints = {
        codigo()
        nombre()
    }
}

grails-app/controllers/encuestador/ListaControladaController.groovy
package encuestador



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class ListaControladaController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond ListaControlada.list(params), model:[listaControladaInstanceCount: ListaControlada.count()]
    }

    def show(ListaControlada listaControladaInstance) {
        respond listaControladaInstance
    }

    def create() {
        respond new ListaControlada(params)
    }

    @Transactional
    def save(ListaControlada listaControladaInstance) {
        if (listaControladaInstance == null) {
            notFound()
            return
        }

        if (listaControladaInstance.hasErrors()) {
            respond listaControladaInstance.errors, view:'create'
            return
        }

        listaControladaInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'listaControlada.label', default: 'ListaControlada'), listaControladaInstance.id])
                redirect listaControladaInstance
            }
            '*' { respond listaControladaInstance, [status: CREATED] }
        }
    }

    def edit(ListaControlada listaControladaInstance) {
        respond listaControladaInstance
    }

    @Transactional
    def update(ListaControlada listaControladaInstance) {
        if (listaControladaInstance == null) {
            notFound()
            return
        }

        if (listaControladaInstance.hasErrors()) {
            respond listaControladaInstance.errors, view:'edit'
            return
        }

        listaControladaInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'ListaControlada.label', default: 'ListaControlada'), listaControladaInstance.id])
                redirect listaControladaInstance
            }
            '*'{ respond listaControladaInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(ListaControlada listaControladaInstance) {

        if (listaControladaInstance == null) {
            notFound()
            return
        }

        listaControladaInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'ListaControlada.label', default: 'ListaControlada'), listaControladaInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'listaControlada.label', default: 'ListaControlada'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/listaControlada/_form.gsp
<%@ page import="encuestador.ListaControlada" %>



<div class="fieldcontain ${hasErrors(bean: listaControladaInstance, field: 'codigo', 'error')} required">
	<label for="codigo">
		<g:message code="listaControlada.codigo.label" default="Codigo" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="codigo" required="" value="${listaControladaInstance?.codigo}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: listaControladaInstance, field: 'nombre', 'error')} required">
	<label for="nombre">
		<g:message code="listaControlada.nombre.label" default="Nombre" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="nombre" required="" value="${listaControladaInstance?.nombre}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: listaControladaInstance, field: 'valores', 'error')} ">
	<label for="valores">
		<g:message code="listaControlada.valores.label" default="Valores" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${listaControladaInstance?.valores?}" var="v">
    <li><g:link controller="valorListaControlada" action="show" id="${v.id}">${v?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="valorListaControlada" action="create" params="['listaControlada.id': listaControladaInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'valorListaControlada.label', default: 'ValorListaControlada')])}</g:link>
</li>
</ul>


</div>

grails-app/views/listaControlada/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'listaControlada.label', default: 'ListaControlada')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-listaControlada" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-listaControlada" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${listaControladaInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${listaControladaInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:listaControladaInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/listaControlada/edit.gsp
<%@ page import="encuestador.ListaControlada" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'listaControlada.label', default: 'ListaControlada')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-listaControlada" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-listaControlada" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${listaControladaInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${listaControladaInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:listaControladaInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${listaControladaInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/listaControlada/index.gsp
<%@ page import="encuestador.ListaControlada" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'listaControlada.label', default: 'ListaControlada')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-listaControlada" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-listaControlada" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="codigo" title="${message(code: 'listaControlada.codigo.label', default: 'Codigo')}" />
					
						<g:sortableColumn property="nombre" title="${message(code: 'listaControlada.nombre.label', default: 'Nombre')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${listaControladaInstanceList}" status="i" var="listaControladaInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${listaControladaInstance.id}">${fieldValue(bean: listaControladaInstance, field: "codigo")}</g:link></td>
					
						<td>${fieldValue(bean: listaControladaInstance, field: "nombre")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${listaControladaInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/listaControlada/show.gsp
<%@ page import="encuestador.ListaControlada" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'listaControlada.label', default: 'ListaControlada')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-listaControlada" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-listaControlada" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list listaControlada">
			
				<g:if test="${listaControladaInstance?.codigo}">
				<li class="fieldcontain">
					<span id="codigo-label" class="property-label"><g:message code="listaControlada.codigo.label" default="Codigo" /></span>
					
						<span class="property-value" aria-labelledby="codigo-label"><g:fieldValue bean="${listaControladaInstance}" field="codigo"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${listaControladaInstance?.nombre}">
				<li class="fieldcontain">
					<span id="nombre-label" class="property-label"><g:message code="listaControlada.nombre.label" default="Nombre" /></span>
					
						<span class="property-value" aria-labelledby="nombre-label"><g:fieldValue bean="${listaControladaInstance}" field="nombre"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${listaControladaInstance?.valores}">
				<li class="fieldcontain">
					<span id="valores-label" class="property-label"><g:message code="listaControlada.valores.label" default="Valores" /></span>
					
						<g:each in="${listaControladaInstance.valores}" var="v">
						<span class="property-value" aria-labelledby="valores-label"><g:link controller="valorListaControlada" action="show" id="${v.id}">${v?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:listaControladaInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${listaControladaInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>