grails-app/domain/encuestador/AsignacionParticipante.groovy
package encuestador

class AsignacionParticipante {

    static belongsTo = [encuestador: Encuestador, participante: ParticipaEn ]

    static constraints = {
    }
}

grails-app/controllers/encuestador/AsignacionParticipanteController.groovy
package encuestador



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class AsignacionParticipanteController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond AsignacionParticipante.list(params), model:[asignacionParticipanteInstanceCount: AsignacionParticipante.count()]
    }

    def show(AsignacionParticipante asignacionParticipanteInstance) {
        respond asignacionParticipanteInstance
    }

    def create() {
        respond new AsignacionParticipante(params)
    }

    @Transactional
    def save(AsignacionParticipante asignacionParticipanteInstance) {
        if (asignacionParticipanteInstance == null) {
            notFound()
            return
        }

        if (asignacionParticipanteInstance.hasErrors()) {
            respond asignacionParticipanteInstance.errors, view:'create'
            return
        }

        asignacionParticipanteInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'asignacionParticipante.label', default: 'AsignacionParticipante'), asignacionParticipanteInstance.id])
                redirect asignacionParticipanteInstance
            }
            '*' { respond asignacionParticipanteInstance, [status: CREATED] }
        }
    }

    def edit(AsignacionParticipante asignacionParticipanteInstance) {
        respond asignacionParticipanteInstance
    }

    @Transactional
    def update(AsignacionParticipante asignacionParticipanteInstance) {
        if (asignacionParticipanteInstance == null) {
            notFound()
            return
        }

        if (asignacionParticipanteInstance.hasErrors()) {
            respond asignacionParticipanteInstance.errors, view:'edit'
            return
        }

        asignacionParticipanteInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'AsignacionParticipante.label', default: 'AsignacionParticipante'), asignacionParticipanteInstance.id])
                redirect asignacionParticipanteInstance
            }
            '*'{ respond asignacionParticipanteInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(AsignacionParticipante asignacionParticipanteInstance) {

        if (asignacionParticipanteInstance == null) {
            notFound()
            return
        }

        asignacionParticipanteInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'AsignacionParticipante.label', default: 'AsignacionParticipante'), asignacionParticipanteInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'asignacionParticipante.label', default: 'AsignacionParticipante'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/asignacionParticipante/_form.gsp
<%@ page import="encuestador.AsignacionParticipante" %>



<div class="fieldcontain ${hasErrors(bean: asignacionParticipanteInstance, field: 'encuestador', 'error')} required">
	<label for="encuestador">
		<g:message code="asignacionParticipante.encuestador.label" default="Encuestador" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="encuestador" name="encuestador.id" from="${encuestador.Encuestador.list()}" optionKey="id" required="" value="${asignacionParticipanteInstance?.encuestador?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: asignacionParticipanteInstance, field: 'participante', 'error')} required">
	<label for="participante">
		<g:message code="asignacionParticipante.participante.label" default="Participante" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="participante" name="participante.id" from="${encuestador.ParticipaEn.list()}" optionKey="id" required="" value="${asignacionParticipanteInstance?.participante?.id}" class="many-to-one"/>

</div>

grails-app/views/asignacionParticipante/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'asignacionParticipante.label', default: 'AsignacionParticipante')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-asignacionParticipante" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-asignacionParticipante" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${asignacionParticipanteInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${asignacionParticipanteInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:asignacionParticipanteInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/asignacionParticipante/edit.gsp
<%@ page import="encuestador.AsignacionParticipante" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'asignacionParticipante.label', default: 'AsignacionParticipante')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-asignacionParticipante" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-asignacionParticipante" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${asignacionParticipanteInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${asignacionParticipanteInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:asignacionParticipanteInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${asignacionParticipanteInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/asignacionParticipante/index.gsp
<%@ page import="encuestador.AsignacionParticipante" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'asignacionParticipante.label', default: 'AsignacionParticipante')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-asignacionParticipante" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-asignacionParticipante" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="asignacionParticipante.encuestador.label" default="Encuestador" /></th>
					
						<th><g:message code="asignacionParticipante.participante.label" default="Participante" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${asignacionParticipanteInstanceList}" status="i" var="asignacionParticipanteInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${asignacionParticipanteInstance.id}">${fieldValue(bean: asignacionParticipanteInstance, field: "encuestador")}</g:link></td>
					
						<td>${fieldValue(bean: asignacionParticipanteInstance, field: "participante")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${asignacionParticipanteInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/asignacionParticipante/show.gsp
<%@ page import="encuestador.AsignacionParticipante" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'asignacionParticipante.label', default: 'AsignacionParticipante')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-asignacionParticipante" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-asignacionParticipante" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list asignacionParticipante">
			
				<g:if test="${asignacionParticipanteInstance?.encuestador}">
				<li class="fieldcontain">
					<span id="encuestador-label" class="property-label"><g:message code="asignacionParticipante.encuestador.label" default="Encuestador" /></span>
					
						<span class="property-value" aria-labelledby="encuestador-label"><g:link controller="encuestador" action="show" id="${asignacionParticipanteInstance?.encuestador?.id}">${asignacionParticipanteInstance?.encuestador?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${asignacionParticipanteInstance?.participante}">
				<li class="fieldcontain">
					<span id="participante-label" class="property-label"><g:message code="asignacionParticipante.participante.label" default="Participante" /></span>
					
						<span class="property-value" aria-labelledby="participante-label"><g:link controller="participaEn" action="show" id="${asignacionParticipanteInstance?.participante?.id}">${asignacionParticipanteInstance?.participante?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:asignacionParticipanteInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${asignacionParticipanteInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>