grails-app/domain/encuestador/Formulario.groovy
package encuestador

import groovy.transform.ToString

@ToString(includes=['titulo','encuesta'], includeNames=true, includePackage=false)
class Formulario {

    String titulo
    String tabla
    String template = ""
    String templateVista = ""
    String scriptValidacion = ""
	String campos
    Boolean obligatorio = true
    Integer orden

    static belongsTo = [edicion: Edicion]
    static constraints = {
        template nullable: true
		scriptValidacion nullable: true
		templateVista nullable: true
		campos nullable: true
        obligatorio nullable: true
    }

    static mapping = {
        scriptValidacion type: 'text'
        template type: 'text'
		templateVista type: 'text'
		campos type: 'text'
    }

	def extraerCampos() {
		def camposRegex = /datos\.\w+/
		
		(this.template =~ /$camposRegex/).collect { '"'+it.tokenize('.')[1]+'"' } as Set
	}

    def beforeInsert() {
        this.campos = extraerCampos()
    }

    def beforeUpdate() {
        this.campos = extraerCampos()
    }
}

grails-app/controllers/encuestador/FormularioController.groovy
package encuestador



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class FormularioController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Formulario.list(params), model:[formularioInstanceCount: Formulario.count()]
    }

    def show(Formulario formularioInstance) {
        respond formularioInstance
    }

    def create() {
        respond new Formulario(params)
    }

    @Transactional
    def save(Formulario formularioInstance) {
        if (formularioInstance == null) {
            notFound()
            return
        }

        if (formularioInstance.hasErrors()) {
            respond formularioInstance.errors, view:'create'
            return
        }

        formularioInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'formulario.label', default: 'Formulario'), formularioInstance.id])
                redirect formularioInstance
            }
            '*' { respond formularioInstance, [status: CREATED] }
        }
    }

    def edit(Formulario formularioInstance) {
        respond formularioInstance
    }

	def obtenerArchivo(ruta) {
		grailsApplication.parentContext.getResource('/..'+ruta)
	}
	
	@Transactional
	def refrescarTemplates(Formulario formularioInstance) {
		def archivoBase = 'f'+formularioInstance.orden
		def dirBase = "/imports/templates/${formularioInstance.edicion.encuesta.codigo}/${formularioInstance.edicion.anio}/"
        def texto = obtenerArchivo(dirBase+archivoBase+'.html').file.getText('UTF-8')
		formularioInstance.template = texto
		texto = obtenerArchivo(dirBase+archivoBase+'_view.html').file.getText('UTF-8')
		formularioInstance.templateVista = texto
		texto = obtenerArchivo(dirBase+archivoBase+'_validacion.js').file.getText('UTF-8')
		formularioInstance.scriptValidacion = texto

		formularioInstance.save flush:true
		request.withFormat {
			'*'{ respond formularioInstance, view: 'show' }
			
		}
	}

    @Transactional
    def obtenerCampos(Formulario formularioInstance) {
		formularioInstance.campos = formularioInstance.extraerCampos()
		
		formularioInstance.save flush:true
		request.withFormat {
			'*'{ respond formularioInstance, view: 'show' }
			
		}
    }
	
    @Transactional
    def update(Formulario formularioInstance) {
        if (formularioInstance == null) {
            notFound()
            return
        }

        if (formularioInstance.hasErrors()) {
            respond formularioInstance.errors, view:'edit'
            return
        }

		formularioInstance.campos = formularioInstance.extraerCampos()

		formularioInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Formulario.label', default: 'Formulario'), formularioInstance.id])
                redirect formularioInstance
            }
            '*'{ respond formularioInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Formulario formularioInstance) {

        if (formularioInstance == null) {
            notFound()
            return
        }

        formularioInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Formulario.label', default: 'Formulario'), formularioInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'formulario.label', default: 'Formulario'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/formulario/_form.gsp
<%@ page import="encuestador.Edicion; encuestador.Formulario" %>



<div class="fieldcontain ${hasErrors(bean: formularioInstance, field: 'edicion', 'error')} required">
	<label for="edicion">
		<g:message code="formulario.edicion.label" default="Edicion" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="edicion" name="edicion.id" from="${encuestador.Edicion.list()}" optionKey="id" required="" value="${formularioInstance?.edicion?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: formularioInstance, field: 'orden', 'error')} required">
	<label for="orden">
		<g:message code="formulario.orden.label" default="Orden" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="orden" type="number" value="${formularioInstance.orden}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: formularioInstance, field: 'tabla', 'error')} required">
	<label for="tabla">
		<g:message code="formulario.tabla.label" default="Tabla" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="tabla" required="" value="${formularioInstance?.tabla}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: formularioInstance, field: 'template', 'error')} required">
	<label for="template">
		<g:message code="formulario.template.label" default="Template" />
		<span class="required-indicator">*</span>
	</label>
    <cmeditor:textArea name="template" binding="vim" required="" value="${formularioInstance?.template}"></cmeditor:textArea>
</div>

<div class="fieldcontain ${hasErrors(bean: formularioInstance, field: 'templateVista', 'error')} required">
	<label for="template">
		<g:message code="formulario.templateVista.label" default="Template Vista" />
		<span class="required-indicator">*</span>
	</label>
    <cmeditor:textArea name="templateVista" binding="vim" required="" value="${formularioInstance?.templateVista}"></cmeditor:textArea>
</div>

<div class="fieldcontain ${hasErrors(bean: formularioInstance, field: 'scriptValidacion', 'error')} required">
    <label for="template">
        <g:message code="formulario.scriptValidacion.label" default="Script Validacion" />
        <span class="required-indicator">*</span>
    </label>
    <cmeditor:textArea name="scriptValidacion" mode="text/javascript" required="" value="${formularioInstance?.scriptValidacion}"></cmeditor:textArea>
</div>

<div class="fieldcontain ${hasErrors(bean: formularioInstance, field: 'titulo', 'error')} required">
	<label for="titulo">
		<g:message code="formulario.titulo.label" default="Titulo" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="titulo" required="" value="${formularioInstance?.titulo}"/>

</div>

<div
		class="fieldcontain ${hasErrors(bean: formularioInstance, field: 'obligatorio', 'error')} ">
	<label for="obligatorio"> <g:message
			code="formulario.obligatorio.label" default="Es Obligatorio?" />

	</label>
	<g:checkBox name="obligatorio" value="${formularioInstance?.obligatorio}" />

</div>

grails-app/views/formulario/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'formulario.label', default: 'Formulario')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-formulario" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-formulario" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${formularioInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${formularioInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:formularioInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/formulario/edit.gsp
<%@ page import="encuestador.Formulario" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'formulario.label', default: 'Formulario')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-formulario" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-formulario" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${formularioInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${formularioInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:formularioInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${formularioInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/formulario/index.gsp
<%@ page import="encuestador.Formulario" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'formulario.label', default: 'Formulario')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-formulario" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-formulario" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="formulario.edicion.label" default="Edicion" /></th>
					
						<g:sortableColumn property="orden" title="${message(code: 'formulario.orden.label', default: 'Orden')}" />
					
						<g:sortableColumn property="tabla" title="${message(code: 'formulario.tabla.label', default: 'Tabla')}" />
					
<%--						<g:sortableColumn property="template" title="${message(code: 'formulario.template.label', default: 'Template')}" />--%>
					
						<g:sortableColumn property="titulo" title="${message(code: 'formulario.titulo.label', default: 'Titulo')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${formularioInstanceList}" status="i" var="formularioInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${formularioInstance.id}">${fieldValue(bean: formularioInstance, field: "edicion")}</g:link></td>
					
						<td>${fieldValue(bean: formularioInstance, field: "orden")}</td>
					
						<td>${fieldValue(bean: formularioInstance, field: "tabla")}</td>
					
<%--						<td>${fieldValue(bean: formularioInstance, field: "template")}</td>--%>
					
						<td>${fieldValue(bean: formularioInstance, field: "titulo")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${formularioInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/formulario/show.gsp
<%@ page import="encuestador.Formulario" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'formulario.label', default: 'Formulario')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-formulario" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-formulario" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list formulario">
			
				<g:if test="${formularioInstance?.edicion}">
				<li class="fieldcontain">
					<span id="edicion-label" class="property-label"><g:message code="formulario.edicion.label" default="edicion" /></span>
					
						<span class="property-value" aria-labelledby="edicion-label"><g:link controller="edicion" action="show" id="${formularioInstance?.edicion?.id}">${formularioInstance?.edicion?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${formularioInstance?.orden}">
				<li class="fieldcontain">
					<span id="orden-label" class="property-label"><g:message code="formulario.orden.label" default="Orden" /></span>
					
						<span class="property-value" aria-labelledby="orden-label"><g:fieldValue bean="${formularioInstance}" field="orden"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${formularioInstance?.tabla}">
				<li class="fieldcontain">
					<span id="tabla-label" class="property-label"><g:message code="formulario.tabla.label" default="Tabla" /></span>
					
						<span class="property-value" aria-labelledby="tabla-label"><g:fieldValue bean="${formularioInstance}" field="tabla"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${formularioInstance?.template}">
				<li class="fieldcontain">
					<span id="template-label" class="property-label"><g:message code="formulario.template.label" default="Template" /></span>
					
						<span class="property-value" aria-labelledby="template-label"><g:fieldValue bean="${formularioInstance}" field="template"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${formularioInstance?.campos}">
				<li class="fieldcontain">
					<span id="template-label" class="property-label"><g:message code="formulario.campos.label" default="Campos" /></span>
					
						<span class="property-value" aria-labelledby="campos-label"><g:fieldValue bean="${formularioInstance}" field="campos"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${formularioInstance?.titulo}">
				<li class="fieldcontain">
					<span id="titulo-label" class="property-label"><g:message code="formulario.titulo.label" default="Titulo" /></span>
					
						<span class="property-value" aria-labelledby="titulo-label"><g:fieldValue bean="${formularioInstance}" field="titulo"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:formularioInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${formularioInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:link class="list" action="refrescarTemplates" resource="${formularioInstance}">Refrescar templates</g:link>
					<g:link class="edit" action="obtenerCampos" resource="${formularioInstance}">Obtener campos</g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>